import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import PDFDocument from 'pdfkit';
import { ANANYA_DOCS, ANANYA_VIDEO_SCRIPT, ROHAN_DOCS, ROHAN_VIDEO_SCRIPT, type DemoDoc } from './documents';

/**
 * Writes the demo papers to disk as real PDFs you can drag into the app during a demo.
 *
 *   npm run demo:docs -w @educaro/api
 *
 * Same files the seed feeds to the pipeline, so what you upload live behaves exactly like what the
 * seeded personas already show — including the planted conflicts.
 */
function render(doc: DemoDoc): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const d = new PDFDocument({ size: 'A4', margin: 56 });
    const chunks: Buffer[] = [];
    d.on('data', (c: Buffer) => chunks.push(c));
    d.on('end', () => resolve(Buffer.concat(chunks)));
    d.on('error', reject);
    doc.build(d);
    d.end();
  });
}

const README = `# Demo documents

Real PDFs, generated by the same code the seed uses. Drag them into the app to watch the pipeline
work on something that was not pre-loaded.

## ananya-nursing/ — GNM nurse, Kochi

Upload all five. Three things are planted in them on purpose, and the agent should find all three:

| What | Where it clashes |
|---|---|
| Her name | The CV says "Ananya Nair". The diploma and the council registration say "ANANYA RAJAN NAIR". |
| Her start date at Amrita | The CV says March 2021. The employer's own letter says 14 June 2021. |
| Her German | The CV claims A2. No certificate exists anywhere in the set. |

She holds a GNM diploma, not a B.Sc. Nursing, so the agent should route her to Ausbildung rather
than the Nursing Program — and say why.

## rohan-masters/ — B.Tech CS, Pune

Upload all four. CGPA 8.2 on a 10 scale, which is 1.9 on the German scale; the transcript lists
every semester's SGPA before the cumulative figure, so check the agent reports 8.2 and not 7.6.
IELTS 7.0 is claimed on the CV with no Test Report Form attached, and APS has not been started.

## intro scripts

\`*-intro-script.txt\` is what to read aloud if you want to record the intro video live. About 60-90
seconds each. Whisper transcribes it and the claims land as "You said", never as Verified.

## Uploading as a brand-new applicant

Sign in with the **fresh** persona for an empty account, record or upload the intro, then drop the
documents in. Everything you see after that was built from these files.
`;

async function main() {
  const root = path.resolve(process.cwd(), '../../demo-documents');
  const sets: [string, DemoDoc[], string, string][] = [
    ['ananya-nursing', ANANYA_DOCS, 'ananya-intro-script.txt', ANANYA_VIDEO_SCRIPT],
    ['rohan-masters', ROHAN_DOCS, 'rohan-intro-script.txt', ROHAN_VIDEO_SCRIPT],
  ];
  for (const [folder, docs, scriptName, script] of sets) {
    const dir = path.join(root, folder);
    await fs.mkdir(dir, { recursive: true });
    for (const doc of docs) {
      await fs.writeFile(path.join(dir, doc.name), await render(doc));
      console.log(`  ${folder}/${doc.name}`);
    }
    await fs.writeFile(path.join(dir, scriptName), script, 'utf8');
    console.log(`  ${folder}/${scriptName}`);
  }
  await fs.writeFile(path.join(root, 'README.md'), README, 'utf8');
  console.log(`\nWritten to ${root}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
